export const AUTHORIZE = 'AUTHORIZE';
export const CHECK_AUTHORIZE = 'CHECK_AUTHORIZE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'