export const AUTHORIZE = 'AUTHORIZE';
export const CHECK_AUTHORIZE = 'CHECK_AUTHORIZE';
export const USER_LOADED = 'USER_LOADED'
export const SET_CURRENT_LIST = 'SET_CURRENT_LIST'
export const GET_LIKED_SONGS = 'GET_LIKED_SONGS'
export const GET_PLAYLIST_SONGS = 'GET_PLAYLIST_SONGS'
export const ITEMS_LOADING = 'ITEMS_LOADING';